legacy_layout=0

fps
frame_timing
gpu_stats
gpu_temp
gpu_power
cpu_stats
cpu_temp
vram
ram

toggle_hud=Shift_R+F12
toggle_fps_limit=Shift_R+F11
toggle_logging=Shift_L+F2

position=top-left
round_corners=10
font_size=24
background_alpha=0.35

# Optional
pci_dev=0:1:0