source = /home/jay/.config/hypr/hyprlock-colors.conf

$font = JetBrainsMono Nerd Font

general {
    hide_cursor = false
}

animations {
    enabled = true

    bezier = smooth, 0.25, 1, 0.5, 1

    animation = fadeIn, 1, 5, smooth
    animation = fadeOut, 1, 5, smooth
    animation = inputFieldDots, 1, 2, smooth
}

background {
    monitor =
    path = screenshot

    blur_size = 6
    blur_passes = 3

    noise = 0.01
    contrast = 0.95
    brightness = 0.72
    vibrancy = 0.18
    vibrancy_darkness = 0.25
}

input-field {
    monitor =

    size = 520, 64
    outline_thickness = 2

    inner_color = $base90
    outer_color = $blue $mauve 45deg
    check_color = $green
    fail_color = $red

    font_color = $text
    font_family = $font

    placeholder_text = <span foreground="##a6adc8">Passwort eingeben …</span>
    fail_text = <span foreground="##f38ba8">Authentifizierung fehlgeschlagen</span>
    check_text = <span foreground="##a6e3a1">Wird entsperrt …</span>

    fade_on_empty = false
    hide_input = false

    dots_spacing = 0.3
    dots_center = true

    rounding = 10

    position = 0, -40
    halign = center
    valign = center
}

label {
    monitor =

    text = $TIME

    color = $blue
    font_family = $font
    font_size = 88

    position = -42, -10
    halign = right
    valign = top
}

label {
    monitor =

    text = cmd[update:60000] date +"%A, %d. %B %Y"

    color = $text
    font_family = $font
    font_size = 24

    position = -44, -145
    halign = right
    valign = top
}

label {
    monitor =

    text = $USER

    color = $subtext0
    font_family = $font
    font_size = 16

    position = 0, 36
    halign = center
    valign = center
}

label {
    monitor =

    text = 󰌌  $LAYOUT[de]

    color = $mauve
    font_family = $font
    font_size = 18

    onclick = hyprctl switchxkblayout all next

    position = 310, -40
    halign = center
    valign = center
}

label {
    monitor =

    text = Zum Entsperren Passwort eingeben

    color = $overlay0
    font_family = $font
    font_size = 13

    position = 0, -98
    halign = center
    valign = center
}
