return {
  lua = { "stylua" },
  javascript = { "prettierd", "prettier" },
  javascriptreact = { "prettierd", "prettier" },
  typescript = { "prettierd", "prettier" },
  typescriptreact = { "prettierd", "prettier" },
  json = { "prettierd", "prettier" },
  html = { "prettierd", "prettier" },
  css = { "prettierd", "prettier" },
  scss = { "prettierd", "prettier" },
  go = { "goimports", "gofumpt" },
  markdown = { "prettier", "markdownlint-cli2", "markdown-toc" },
  ["markdown.mdx"] = { "prettier", "markdownlint-cli2", "markdown-toc" },
  templ = { "gofumpt", "templ" },
}
