-- Neovim Options
-- Link: https://neovim.io/doc/user/options.html#options

local indent = 2

vim.o.autoindent = true
vim.o.autoread = true
vim.o.background = "dark"
vim.o.clipboard = "unnamedplus"
vim.o.cmdheight = 2
vim.o.completeopt = "menu,menuone,noinsert"
vim.o.conceallevel = 0
vim.o.confirm = true
vim.o.copyindent = true
vim.o.cursorcolumn = false
vim.o.cursorline = true
vim.o.expandtab = true
vim.o.icon = true
vim.o.iconstring = ""
vim.o.ignorecase = true
vim.o.laststatus = 1
vim.o.mouse = "a"
vim.o.number = true
vim.o.pumblend = 12
vim.o.pumheight = 8
vim.o.relativenumber = true
vim.o.scrolloff = 8
vim.o.shiftwidth = indent
vim.o.showmode = false
vim.o.sidescrolloff = 8
vim.o.signcolumn = "yes"
vim.o.smartcase = true
vim.o.smartindent = true
vim.o.smarttab = true
vim.o.softtabstop = indent
vim.o.splitbelow = true
vim.o.splitkeep = "screen"
vim.o.splitright = true
vim.o.swapfile = false
vim.o.tabstop = indent
vim.o.termguicolors = true
vim.o.timeoutlen = 250
vim.o.title = true
vim.o.updatetime = 400
vim.o.wrap = false
vim.o.writebackup = false
