return {
	"scottmckendry/cyberdream.nvim",
	priority = 1000,
	config = function()
		require("cyberdream").setup({
			variant = "default",
			transparent = false,
			saturation = 1,
			italic_comments = true,
			hide_fillchars = true,
			borderless_pickers = false,
			terminal_colors = true,
			cache = true,
			extensions = {
				alpha = false,
				blinkcmp = true,
				cmp = false,
				dashboard = false,
				fzflua = false,
				gitpad = false,
				gitsigns = true,
				grapple = false,
				grugfar = true,
				heirline = false,
				helpview = true,
				hop = false,
				indentblankline = false,
				kubectl = false,
				lazy = true,
				leap = false,
				markdown = true,
				markview = false,
				mini = true,
				noice = false,
				neogit = false,
				notify = true,
				rainbow_delimiters = false,
				snacks = true,
				telescope = false,
				treesitter = true,
				treesittercontext = false,
				trouble = true,
				whichkey = true,
			},
		})
		vim.cmd("colorscheme cyberdream")
	end,
}
